; AUTO-GENERATED by offsets.py — do not edit manually
; MINT_SZ=40  TOKEN_SZ=72  MAX_REALLOC=10240  FIXED_FIELDS=0x58

; ── Input buffer ──────────────────────────────────────────
.equ NUM_ACCOUNTS,                      0x0
.equ FIRST_ACCT,                        0x8

; ── Per-account field offsets (from account base) ─────────
.equ ACCT_DUP,                          0x0   ; u8  dup_info (0xFF = not dup)
.equ ACCT_IS_SIGNER,                    0x1   ; u8
.equ ACCT_IS_WRITE,                     0x2   ; u8
.equ ACCT_EXEC,                         0x3   ; u8
.equ ACCT_KEY,                          0x8   ; [u8;32] pubkey
.equ ACCT_OWNER,                        0x28   ; [u8;32] owner program
.equ ACCT_LAMPORTS,                     0x48   ; u64
.equ ACCT_DLEN,                         0x50   ; u64 data length
.equ ACCT_DATA,                         0x58   ; data start
.equ ACCT_RENT_ZERO,                    0x2858   ; rent_epoch offset for zero-data acct (matches escrow ACCT_RENT)
.equ ACCT_RENT_MINT,                    0x2880   ; rent_epoch offset for mint acct
.equ ACCT_RENT_TOKEN,                   0x28a0   ; rent_epoch offset for token acct

; ── Account sizes ─────────────────────────────────────────
.equ MINT_SZ,                           0x28   ; 32b authority + 8b total_minted
.equ TOKEN_SZ,                          0x48   ; 32b mint + 32b authority + 8b balance

; ── Token account data offsets (from ACCT_DATA) ───────────
.equ TA_MINT,                           0x0   ; [u8;32] mint pubkey
.equ TA_AUTHORITY,                      0x20   ; [u8;32] authority pubkey
.equ TA_BALANCE,                        0x40   ; u64 balance

; ── Mint account data offsets (from ACCT_DATA) ────────────
.equ MA_AUTHORITY,                      0x0   ; [u8;32] mint authority pubkey
.equ MA_TOTAL_MINTED,                   0x20   ; u64 total tokens ever minted minus burned

; ── Instruction discriminators  (Transfer has no disc — detected by data_len==8)
.equ IX_MINT_TO,                        0x0
.equ IX_SET_AUTHORITY,                  0x1
.equ IX_BURN,                           0x2
.equ IX_INIT_MINT,                      0x3
.equ IX_INIT_TOKEN,                     0x4
.equ IX_CLOSE,                          0x5

; ── Error codes ───────────────────────────────────────────
.equ ERR_INVALID_IX,                    0x1
.equ ERR_WRONG_ACCT_COUNT,              0x2
.equ ERR_NOT_SIGNER,                    0x3
.equ ERR_NOT_WRITABLE,                  0x4
.equ ERR_WRONG_ACCT_SIZE,               0x5
.equ ERR_MINT_MISMATCH,                 0x6
.equ ERR_AUTHORITY_MISMATCH,            0x7
.equ ERR_INSUFFICIENT_BALANCE,          0x8
.equ ERR_OVERFLOW,                      0x9
.equ ERR_ZERO_AMOUNT,                   0xa
.equ ERR_ALREADY_INITIALIZED,           0xb
.equ ERR_SUPPLY_UNDERFLOW,              0xc
.equ ERR_NONZERO_BALANCE,               0xd

; ── Stride verification (dynamic account walking) ─────────
; stride(zero-data) = 0x2860  (10336 bytes)
; stride(mint     ) = 0x2888  (10376 bytes)
; stride(token    ) = 0x28a8  (10408 bytes)

; All assertions passed.


.globl entrypoint
entrypoint:
    ; ── find ix_data by walking accounts ──────────────────────
    ldxdw r6, [r1 + 0]         ; r6 = num_accounts (loop counter)
    mov64 r7, r1
    add64 r7, 8                ; r7 = cursor (advances to each account, then ix_data)
    mov64 r2, r10
    sub64 r2, 8                ; r2 = moving stack ptr (r10-8, r10-16, ...)

find_ix_data_loop:
    jeq   r6, 0, find_ix_data_done
    stxdw [r2 + 0], r7         ; save account base ptr to stack
    sub64 r2, 8                ; advance stack ptr to next slot
    ldxdw r3, [r7 + ACCT_DLEN]
    add64 r3, 10247            ; data_len + 10240 + 7 (align8 prep, combined)
    mov64 r4, r3
    and64 r4, 7                ; r4 = remainder
    sub64 r3, r4               ; r3 = align8(data_len + 10240)
    add64 r3, 96               ; + fixed fields (88) + rent (8)
    add64 r7, r3               ; advance cursor to next account
    sub64 r6, 1
    ja    find_ix_data_loop

find_ix_data_done:
    ; r7 = ix_data_len pointer
    ldxdw r3, [r7 + 0]         ; r3 = data_len

    ; transfer: no disc, detected by data_len == 8
    jeq   r3, 8, transfer

    ; all others need at least 1 byte
    jlt   r3, 1, err_invalid_ix

    ldxb  r4, [r7 + 8]         ; r4 = discriminator

    jeq   r4, IX_MINT_TO,       mint_to
    jeq   r4, IX_SET_AUTHORITY, set_authority
    jeq   r4, IX_BURN,          burn
    jeq   r4, IX_INIT_MINT,     init_mint
    jeq   r4, IX_INIT_TOKEN,    init_token
    jeq   r4, IX_CLOSE,         close_account
    ja    err_invalid_ix

; ── Instruction stubs ─────────────────────────────────────────────────

transfer:
    ldxdw r2, [r1 + NUM_ACCOUNTS]
    jne r2, 3, err_wrong_acct_count

    ldxdw r6, [r10 - 8]                             ; r6 = acct0 (src)
    ldxdw r8, [r10 - 16]                             ; r8 = acct1 (dest)
    ldxdw r9, [r10 - 24]                            ; r10 = acct2 (authority)

    ldxb r4, [r6 + ACCT_DUP]
    jne r4, 0xFF, err_wrong_acct_count              ;check dup
    ldxb r4, [r6 + ACCT_IS_WRITE]
    jne r4, 1, err_not_writable                     ;check is writable

    ldxb r4, [r8 + ACCT_DUP]
    jne r4, 0xFF, err_wrong_acct_count              ;check dup
    ldxb r4, [r8 + ACCT_IS_WRITE]
    jne r4, 1, err_not_writable                     ;check is writable

    ldxb r4, [r9 + ACCT_DUP]
    jne r4, 0xFF, err_wrong_acct_count              ;check dup
    ldxb r4, [r9 + ACCT_IS_SIGNER]
    jne r4, 1, err_not_signer                       ;check is signer

    ldxdw r4, [r6 + ACCT_DLEN]
    jne r4, TOKEN_SZ, err_wrong_acct_size           ; check token size

    ldxdw r4, [r8 + ACCT_DLEN]
    jne r4, TOKEN_SZ, err_wrong_acct_size           ; check token size

    ; src.mint == dest.mint
    mov64 r1, r6
    add64 r1, ACCT_DATA
    mov64 r2, r8
    add64 r2, ACCT_DATA
    call cmp32
    jne r0, 0, err_mint_mismatch

    ; src.authority == authority.key
    mov64 r1, r6
    add64 r1, ACCT_DATA
    add64 r1, TA_AUTHORITY
    mov64 r2, r9
    add64 r2, ACCT_KEY
    call cmp32
    jne r0, 0, err_authority_mismatch

    ldxdw r2, [r7 + 8]          ; transfer amount

    ; src.balance >= transfer amount
    ldxdw r3, [r6 + ACCT_DATA + TA_BALANCE]
    jgt r2, r3, err_insufficient_balance

    ldxdw r4, [r8 + ACCT_DATA + TA_BALANCE]
    mov64 r5, r4
    add64 r5, r2
    jlt r5, r4, err_overflow

    sub64 r3, r2
    stxdw [r6 + ACCT_DATA + TA_BALANCE], r3   ; src.balance -= amount
    stxdw [r8 + ACCT_DATA + TA_BALANCE], r5   ; dst.balance += amount
    mov64 r0, 0
    exit

mint_to:
    ldxdw r2, [r1 + NUM_ACCOUNTS]
    jne r2, 2, err_wrong_acct_count

    ldxdw r6, [r10 - 8]                             ; r6 = acct0 (mint)
    ldxdw r8, [r10 - 16]                             ; r8 = acct1 (token)

    ldxb r4, [r6 + ACCT_DUP]
    jne r4, 0xFF, err_wrong_acct_count              ;check dup
    ldxb r4, [r6 + ACCT_IS_WRITE]
    jne r4, 1, err_not_writable                     ;check is writable
    ldxb r4, [r6 + ACCT_IS_SIGNER]
    jne r4, 1, err_not_signer                       ;check is signer

    ldxb r4, [r8 + ACCT_DUP]
    jne r4, 0xFF, err_wrong_acct_count              ;check dup
    ldxb r4, [r8 + ACCT_IS_WRITE]
    jne r4, 1, err_not_writable                     ;check is writable

    ldxdw r4, [r6 + ACCT_DLEN]
    jne r4, MINT_SZ, err_wrong_acct_size           ; check mint size

    ldxdw r4, [r8 + ACCT_DLEN]
    jne r4, TOKEN_SZ, err_wrong_acct_size           ; check token size

    jne r3, 9, err_invalid_ix                       ;check ix data len

    ;mint.key == token.mint
    mov64 r1, r6
    add64 r1, ACCT_KEY
    mov64 r2, r8
    add64 r2, ACCT_DATA
    add64 r2, TA_MINT
    call cmp32
    jne r0, 0, err_mint_mismatch

    ldxdw r2, [r7 + 9]
    jeq r2, 0, err_zero_amount

    ;token.balance += amount
    ldxdw r3, [r8 + ACCT_DATA + TA_BALANCE]
    mov64 r4, r3
    add64 r4, r2
    jlt r4, r3, err_overflow
    stxdw [r8 + ACCT_DATA + TA_BALANCE], r4

    ;mint.total_minted += amount
    ldxdw r3, [r6 + ACCT_DATA + MA_TOTAL_MINTED]
    mov64 r4, r3
    add64 r4, r2
    jlt r4, r3, err_overflow
    stxdw [r6 + ACCT_DATA + MA_TOTAL_MINTED], r4

    mov64 r0, 0
    exit

set_authority:
    mov64 r0, 0
    exit

burn:
    mov64 r0, 0
    exit

init_mint:
    ldxdw r2, [r1 + NUM_ACCOUNTS]
    jne r2, 1, err_wrong_acct_count

    ldxdw r2, [r10 - 8]                             ;mint acc (acct0)
    ldxb r4, [r2 + ACCT_IS_SIGNER]
    jne r4, 1, err_not_signer                       ;check is signer

    ldxb r4, [r2 + ACCT_DUP]
    jne r4, 0xFF, err_wrong_acct_count              ;check dup

    ldxb r4, [r2 + ACCT_IS_WRITE]
    jne r4, 1, err_not_writable                     ;check is writable

    ldxdw r4, [r2 + ACCT_DLEN]
    jne r4, MINT_SZ, err_wrong_acct_size            ;check acct size

    jne r3, 33, err_invalid_ix                       ;check ix data len

    ldxdw r4, [r2 + ACCT_DATA + MA_TOTAL_MINTED]
    jne r4, 0, err_already_initialized               ;check already initialized

    mov64 r1, r2
    add64 r1, ACCT_DATA
    mov64 r2, r7
    add64 r2, 9
    call copy32     ;copy authority to mint acc

    mov64 r0, 0
    exit

init_token:
    ldxdw r2, [r1 + NUM_ACCOUNTS]
    jne r2, 2, err_wrong_acct_count

    ldxdw r6, [r10 - 8]                             ; r6 = acct0 (token)
    ldxdw r8, [r10 - 16]                             ; r8 = acct1 (mint)

    ldxb r4, [r6 + ACCT_DUP]
    jne r4, 0xFF, err_wrong_acct_count              ; check token dup

    ldxb r4, [r6 + ACCT_IS_WRITE]
    jne r4, 1, err_not_writable                     ; check token writable

    ldxdw r4, [r6 + ACCT_DLEN]
    jne r4, TOKEN_SZ, err_wrong_acct_size           ; check token size

    jne r3, 33, err_invalid_ix                      ; check ix data len

    ldxdw r5, [r6 + ACCT_DATA + TA_MINT + 0]
    ldxdw r4, [r6 + ACCT_DATA + TA_MINT + 8]
    or64  r5, r4
    ldxdw r4, [r6 + ACCT_DATA + TA_MINT + 16]
    or64  r5, r4
    ldxdw r4, [r6 + ACCT_DATA + TA_MINT + 24]
    or64  r5, r4
    jne   r5, 0, err_already_initialized            ; check not already initialized

    ldxb r4, [r8 + ACCT_DUP]
    jne r4, 0xFF, err_wrong_acct_count              ; check mint dup

    ldxdw r4, [r8 + ACCT_DLEN]
    jne r4, MINT_SZ, err_wrong_acct_size            ; check mint size

    ; copy acct1.key → token.data[TA_MINT]
    mov64 r1, r6
    add64 r1, ACCT_DATA                             ; dst: TA_MINT=0x00 so no extra offset
    mov64 r2, r8
    add64 r2, ACCT_KEY                              ; src: acct1.key
    call copy32                                     ; clobbers r1, r2, r3

    ; copy ix_data[1..33] → token.data[TA_AUTHORITY]
    mov64 r1, r6
    add64 r1, ACCT_DATA
    add64 r1, TA_AUTHORITY
    mov64 r2, r7
    add64 r2, 9
    call copy32                                     ; clobbers r1, r2, r3

    ; zero TA_BALANCE
    mov64 r3, 0
    stxdw [r6 + ACCT_DATA + TA_BALANCE], r3

    mov64 r0, 0
    exit

close_account:
    mov64 r0, 0
    exit

; ── Errors ────────────────────────────────────────────────────────────

err_invalid_ix:
    mov64 r0, ERR_INVALID_IX
    exit

err_wrong_acct_count:
    mov64 r0, ERR_WRONG_ACCT_COUNT
    exit

err_not_signer:
    mov64 r0, ERR_NOT_SIGNER
    exit

err_not_writable:
    mov64 r0, ERR_NOT_WRITABLE
    exit

err_wrong_acct_size:
    mov64 r0, ERR_WRONG_ACCT_SIZE
    exit

err_mint_mismatch:
    mov64 r0, ERR_MINT_MISMATCH
    exit

err_authority_mismatch:
    mov64 r0, ERR_AUTHORITY_MISMATCH
    exit

err_insufficient_balance:
    mov64 r0, ERR_INSUFFICIENT_BALANCE
    exit

err_overflow:
    mov64 r0, ERR_OVERFLOW
    exit

err_zero_amount:
    mov64 r0, ERR_ZERO_AMOUNT
    exit

err_already_initialized:
    mov64 r0, ERR_ALREADY_INITIALIZED
    exit

err_supply_underflow:
    mov64 r0, ERR_SUPPLY_UNDERFLOW
    exit

err_nonzero_balance:
    mov64 r0, ERR_NONZERO_BALANCE
    exit

; ── Helpers ───────────────────────────────────────────────────────────

cmp32:
    ldxdw r3, [r1 + 0]
    ldxdw r4, [r2 + 0]
    jne r3, r4, cmp32_ne
    ldxdw r3, [r1 + 8]
    ldxdw r4, [r2 + 8]
    jne r3, r4, cmp32_ne
    ldxdw r3, [r1 + 16]
    ldxdw r4, [r2 + 16]
    jne r3, r4, cmp32_ne
    ldxdw r3, [r1 + 24]
    ldxdw r4, [r2 + 24]
    jne r3, r4, cmp32_ne
    mov64 r0, 0
    exit
cmp32_ne:
    mov64 r0, 1
    exit

copy32:
    ldxdw r3, [r2 + 0]
    stxdw [r1 + 0], r3
    ldxdw r3, [r2 + 8]
    stxdw [r1 + 8], r3
    ldxdw r3, [r2 + 16]
    stxdw [r1 + 16], r3
    ldxdw r3, [r2 + 24]
    stxdw [r1 + 24], r3
    exit
