; AUTO-GENERATED by offsets.py — do not edit manually
; MINT_SZ=40  TOKEN_SZ=72  MAX_REALLOC=10240  FIXED_FIELDS=0x58

; ── Input buffer ──────────────────────────────────────────
.equ NUM_ACCOUNTS,                      0x0
.equ FIRST_ACCT,                        0x8

; ── Per-account field offsets (from account base) ─────────
.equ ACCT_DUP,                          0x0   ; u8  dup_info (0xFF = not dup)
.equ ACCT_IS_SIGNER,                    0x1   ; u8
.equ ACCT_IS_WRITE,                     0x2   ; u8
.equ ACCT_EXEC,                         0x3   ; u8
.equ ACCT_KEY,                          0x8   ; [u8;32] pubkey
.equ ACCT_OWNER,                        0x28   ; [u8;32] owner program
.equ ACCT_LAMPORTS,                     0x48   ; u64
.equ ACCT_DLEN,                         0x50   ; u64 data length
.equ ACCT_DATA,                         0x58   ; data start
.equ ACCT_RENT_ZERO,                    0x2858   ; rent_epoch offset for zero-data acct (matches escrow ACCT_RENT)
.equ ACCT_RENT_MINT,                    0x2880   ; rent_epoch offset for mint acct
.equ ACCT_RENT_TOKEN,                   0x28a0   ; rent_epoch offset for token acct

; ── Account sizes ─────────────────────────────────────────
.equ MINT_SZ,                           0x28   ; 32b authority + 8b total_minted
.equ TOKEN_SZ,                          0x48   ; 32b mint + 32b authority + 8b balance

; ── Token account data offsets (from ACCT_DATA) ───────────
.equ TA_MINT,                           0x0   ; [u8;32] mint pubkey
.equ TA_AUTHORITY,                      0x20   ; [u8;32] authority pubkey
.equ TA_BALANCE,                        0x40   ; u64 balance

; ── Mint account data offsets (from ACCT_DATA) ────────────
.equ MA_AUTHORITY,                      0x0   ; [u8;32] mint authority pubkey
.equ MA_TOTAL_MINTED,                   0x20   ; u64 total tokens ever minted minus burned

; ── Instruction discriminators  (Transfer has no disc — detected by data_len==8)
.equ IX_MINT_TO,                        0x0
.equ IX_SET_AUTHORITY,                  0x1
.equ IX_BURN,                           0x2
.equ IX_INIT_MINT,                      0x3
.equ IX_INIT_TOKEN,                     0x4
.equ IX_CLOSE,                          0x5

; ── Error codes ───────────────────────────────────────────
.equ ERR_INVALID_IX,                    0x1
.equ ERR_WRONG_ACCT_COUNT,              0x2
.equ ERR_NOT_SIGNER,                    0x3
.equ ERR_NOT_WRITABLE,                  0x4
.equ ERR_WRONG_ACCT_SIZE,               0x5
.equ ERR_MINT_MISMATCH,                 0x6
.equ ERR_AUTHORITY_MISMATCH,            0x7
.equ ERR_INSUFFICIENT_BALANCE,          0x8
.equ ERR_OVERFLOW,                      0x9
.equ ERR_ZERO_AMOUNT,                   0xa
.equ ERR_ALREADY_INITIALIZED,           0xb
.equ ERR_SUPPLY_UNDERFLOW,              0xc
.equ ERR_NONZERO_BALANCE,               0xd

; ── Stride verification (dynamic account walking) ─────────
; stride(zero-data) = 0x2860  (10336 bytes)
; stride(mint     ) = 0x2888  (10376 bytes)
; stride(token    ) = 0x28a8  (10408 bytes)

; All assertions passed.


.globl entrypoint
entrypoint:
    ; ── find ix_data by walking accounts (copy from escrow) ──
    ldxdw r6, [r1 + 0]
    mov64 r7, r1
    add64 r7, 8

find_ix_data_loop:
    jeq   r6, 0, find_ix_data_done
    mov64 r3, r9
    lsh64 r3, 3
    mov64 r2, r10
    sub64 r2, 8
    sub64 r2, r3
    stxdw [r2 + 0], r7
    add64 r9, 1
    ldxdw r2, [r7 + ACCT_DLEN]
    add64 r2, 10240
    add64 r2, 7
    mov64 r3, r2
    and64 r3, 7
    sub64 r2, r3
    add64 r2, 96
    add64 r7, r2
    sub64 r6, 1
    ja    find_ix_data_loop

find_ix_data_done:
    ; r7 = ix_data_len pointer
    ldxdw r3, [r7 + 0]         ; r3 = data_len

    ; transfer: no disc, detected by data_len == 8
    jeq   r3, 8, transfer

    ; all others need at least 1 byte
    jlt   r3, 1, err_invalid_ix

    ldxb  r4, [r7 + 8]         ; r4 = discriminator

    jeq   r4, IX_MINT_TO,       mint_to
    jeq   r4, IX_SET_AUTHORITY, set_authority
    jeq   r4, IX_BURN,          burn
    jeq   r4, IX_INIT_MINT,     init_mint
    jeq   r4, IX_INIT_TOKEN,    init_token
    jeq   r4, IX_CLOSE,         close_account
    ja    err_invalid_ix

; ── Instruction stubs ─────────────────────────────────────────────────

transfer:
    mov64 r0, 0
    exit

mint_to:
    mov64 r0, 0
    exit

set_authority:
    mov64 r0, 0
    exit

burn:
    mov64 r0, 0
    exit

init_mint:
    mov64 r0, 0
    exit

init_token:
    mov64 r0, 0
    exit

close_account:
    mov64 r0, 0
    exit

; ── Errors ────────────────────────────────────────────────────────────

err_invalid_ix:
    mov64 r0, ERR_INVALID_IX
    exit

err_wrong_acct_count:
    mov64 r0, ERR_WRONG_ACCT_COUNT
    exit

err_not_signer:
    mov64 r0, ERR_NOT_SIGNER
    exit

err_not_writable:
    mov64 r0, ERR_NOT_WRITABLE
    exit

err_wrong_acct_size:
    mov64 r0, ERR_WRONG_ACCT_SIZE
    exit

err_mint_mismatch:
    mov64 r0, ERR_MINT_MISMATCH
    exit

err_authority_mismatch:
    mov64 r0, ERR_AUTHORITY_MISMATCH
    exit

err_insufficient_balance:
    mov64 r0, ERR_INSUFFICIENT_BALANCE
    exit

err_overflow:
    mov64 r0, ERR_OVERFLOW
    exit

err_zero_amount:
    mov64 r0, ERR_ZERO_AMOUNT
    exit

err_already_initialized:
    mov64 r0, ERR_ALREADY_INITIALIZED
    exit

err_supply_underflow:
    mov64 r0, ERR_SUPPLY_UNDERFLOW
    exit

err_nonzero_balance:
    mov64 r0, ERR_NONZERO_BALANCE
    exit

; ── Helpers ───────────────────────────────────────────────────────────

cmp32:
    ldxdw r3, [r1 + 0]
    ldxdw r4, [r2 + 0]
    jne r3, r4, cmp32_ne
    ldxdw r3, [r1 + 8]
    ldxdw r4, [r2 + 8]
    jne r3, r4, cmp32_ne
    ldxdw r3, [r1 + 16]
    ldxdw r4, [r2 + 16]
    jne r3, r4, cmp32_ne
    ldxdw r3, [r1 + 24]
    ldxdw r4, [r2 + 24]
    jne r3, r4, cmp32_ne
    mov64 r0, 0
    exit
cmp32_ne:
    mov64 r0, 1
    exit

copy32:
    ldxdw r3, [r2 + 0]
    stxdw [r1 + 0], r3
    ldxdw r3, [r2 + 8]
    stxdw [r1 + 8], r3
    ldxdw r3, [r2 + 16]
    stxdw [r1 + 16], r3
    ldxdw r3, [r2 + 24]
    stxdw [r1 + 24], r3
    exit
