#!/usr/bin/env python3
"""
offsets.py — Pre-calculate all byte offsets for token.s

Run before writing assembly. All assertions must pass.
Output is valid .equ defines — pipe to a file or copy into token.s.

Usage:
    python3 src/offsets.py
    python3 src/offsets.py > src/offsets.s
"""

# ── Account layout constants ──────────────────────────────────────────

FIXED_FIELDS  = 0x58   # bytes before data: 8(hdr) + 32(key) + 32(owner) + 8(lamps) + 8(dlen)
MAX_REALLOC   = 10240
RENT_SIZE     = 8

MINT_SZ  = 40   # 32b authority + 8b total_minted
TOKEN_SZ = 72   # 32b mint + 32b authority + 8b balance

# ── Per-account field offsets (from account base) ─────────────────────

ACCT_DUP      = 0x00
ACCT_SIGNER   = 0x01
ACCT_WRITE    = 0x02
ACCT_EXEC     = 0x03
ACCT_KEY      = 0x08
ACCT_OWNER    = 0x28
ACCT_LAMPORTS = 0x48
ACCT_DLEN     = 0x50
ACCT_DATA     = 0x58

# ── Token account data offsets (from ACCT_DATA) ───────────────────────

TA_MINT      = 0x00   # [u8;32]
TA_AUTHORITY = 0x20   # [u8;32]
TA_BALANCE   = 0x40   # u64

# ── Mint account data offsets (from ACCT_DATA) ────────────────────────

MA_AUTHORITY    = 0x00   # [u8;32]
MA_TOTAL_MINTED = 0x20   # u64

# ── Instruction discriminators ────────────────────────────────────────

IX_MINT_TO       = 0
IX_SET_AUTHORITY = 1
IX_BURN          = 2
IX_INIT_MINT     = 3
IX_INIT_TOKEN    = 4
IX_CLOSE         = 5

# ── Error codes ───────────────────────────────────────────────────────

ERR_INVALID_IX            = 0x01
ERR_WRONG_ACCT_COUNT      = 0x02
ERR_NOT_SIGNER            = 0x03
ERR_NOT_WRITABLE          = 0x04
ERR_WRONG_ACCT_SIZE       = 0x05
ERR_MINT_MISMATCH         = 0x06
ERR_AUTHORITY_MISMATCH    = 0x07
ERR_INSUFFICIENT_BALANCE  = 0x08
ERR_OVERFLOW              = 0x09
ERR_ZERO_AMOUNT           = 0x0A
ERR_ALREADY_INITIALIZED   = 0x0B
ERR_SUPPLY_UNDERFLOW      = 0x0C
ERR_NONZERO_BALANCE       = 0x0D

# ── Helpers ───────────────────────────────────────────────────────────

def align8(n):
    return (n + 7) & ~7

def stride(data_len):
    """Bytes from one account base to the next (dynamic walk formula)."""
    return FIXED_FIELDS + align8(data_len + MAX_REALLOC) + RENT_SIZE

def rent_off(data_len):
    """Offset of rent_epoch from account base, for a given data_len."""
    return ACCT_DATA + align8(data_len + MAX_REALLOC)

# ── Assertions ────────────────────────────────────────────────────────

assert stride(0)        == 0x2860, f"stride(0)={hex(stride(0))} expected 0x2860 — MAX_REALLOC wrong?"
assert stride(TOKEN_SZ) == 0x28A8, f"stride(TOKEN_SZ)={hex(stride(TOKEN_SZ))} expected 0x28A8"
assert rent_off(0)      == 0x2858, f"rent_off(0)={hex(rent_off(0))} expected 0x2858 — matches ACCT_RENT in escrow"

assert TA_MINT      + 32 == TA_AUTHORITY,         "TA_MINT and TA_AUTHORITY not contiguous"
assert TA_AUTHORITY + 32 == TA_BALANCE,            "TA_AUTHORITY and TA_BALANCE not contiguous"
assert TA_BALANCE   +  8 == TOKEN_SZ,              "TOKEN_SZ wrong"
assert MA_AUTHORITY + 32 == MA_TOTAL_MINTED,       "MA_AUTHORITY and MA_TOTAL_MINTED not contiguous"
assert MA_TOTAL_MINTED + 8 == MINT_SZ,             "MINT_SZ wrong"

# ── Output ────────────────────────────────────────────────────────────

def equ(name, val, comment=""):
    pad = max(1, 34 - len(name))
    c = f"   ; {comment}" if comment else ""
    print(f".equ {name},{' ' * pad}{hex(val)}{c}")

def sep(title):
    bar = "─" * (54 - len(title))
    print(f"\n; ── {title} {bar}")

print("; AUTO-GENERATED by offsets.py — do not edit manually")
print(f"; MINT_SZ={MINT_SZ}  TOKEN_SZ={TOKEN_SZ}  MAX_REALLOC={MAX_REALLOC}  FIXED_FIELDS={hex(FIXED_FIELDS)}")

sep("Input buffer")
equ("NUM_ACCOUNTS",          0x0000)
equ("FIRST_ACCT",            0x0008)

sep("Per-account field offsets (from account base)")
equ("ACCT_DUP",              ACCT_DUP,              "u8  dup_info (0xFF = not dup)")
equ("ACCT_IS_SIGNER",        ACCT_SIGNER,            "u8")
equ("ACCT_IS_WRITE",         ACCT_WRITE,             "u8")
equ("ACCT_EXEC",             ACCT_EXEC,              "u8")
equ("ACCT_KEY",              ACCT_KEY,               "[u8;32] pubkey")
equ("ACCT_OWNER",            ACCT_OWNER,             "[u8;32] owner program")
equ("ACCT_LAMPORTS",         ACCT_LAMPORTS,          "u64")
equ("ACCT_DLEN",             ACCT_DLEN,              "u64 data length")
equ("ACCT_DATA",             ACCT_DATA,              "data start")
equ("ACCT_RENT_ZERO",        rent_off(0),            "rent_epoch offset for zero-data acct (matches escrow ACCT_RENT)")
equ("ACCT_RENT_MINT",        rent_off(MINT_SZ),      "rent_epoch offset for mint acct")
equ("ACCT_RENT_TOKEN",       rent_off(TOKEN_SZ),     "rent_epoch offset for token acct")

sep("Account sizes")
equ("MINT_SZ",               MINT_SZ,                "32b authority + 8b total_minted")
equ("TOKEN_SZ",              TOKEN_SZ,               "32b mint + 32b authority + 8b balance")

sep("Token account data offsets (from ACCT_DATA)")
equ("TA_MINT",               TA_MINT,                "[u8;32] mint pubkey")
equ("TA_AUTHORITY",          TA_AUTHORITY,           "[u8;32] authority pubkey")
equ("TA_BALANCE",            TA_BALANCE,             "u64 balance")

sep("Mint account data offsets (from ACCT_DATA)")
equ("MA_AUTHORITY",          MA_AUTHORITY,           "[u8;32] mint authority pubkey")
equ("MA_TOTAL_MINTED",       MA_TOTAL_MINTED,        "u64 total tokens ever minted minus burned")

sep("Instruction discriminators  (Transfer has no disc — detected by data_len==8)")
equ("IX_MINT_TO",            IX_MINT_TO)
equ("IX_SET_AUTHORITY",      IX_SET_AUTHORITY)
equ("IX_BURN",               IX_BURN)
equ("IX_INIT_MINT",          IX_INIT_MINT)
equ("IX_INIT_TOKEN",         IX_INIT_TOKEN)
equ("IX_CLOSE",              IX_CLOSE)

sep("Error codes")
equ("ERR_INVALID_IX",            ERR_INVALID_IX)
equ("ERR_WRONG_ACCT_COUNT",      ERR_WRONG_ACCT_COUNT)
equ("ERR_NOT_SIGNER",            ERR_NOT_SIGNER)
equ("ERR_NOT_WRITABLE",          ERR_NOT_WRITABLE)
equ("ERR_WRONG_ACCT_SIZE",       ERR_WRONG_ACCT_SIZE)
equ("ERR_MINT_MISMATCH",         ERR_MINT_MISMATCH)
equ("ERR_AUTHORITY_MISMATCH",    ERR_AUTHORITY_MISMATCH)
equ("ERR_INSUFFICIENT_BALANCE",  ERR_INSUFFICIENT_BALANCE)
equ("ERR_OVERFLOW",              ERR_OVERFLOW)
equ("ERR_ZERO_AMOUNT",           ERR_ZERO_AMOUNT)
equ("ERR_ALREADY_INITIALIZED",   ERR_ALREADY_INITIALIZED)
equ("ERR_SUPPLY_UNDERFLOW",      ERR_SUPPLY_UNDERFLOW)
equ("ERR_NONZERO_BALANCE",       ERR_NONZERO_BALANCE)

sep("Stride verification (dynamic account walking)")
for d, label in [(0, "zero-data"), (MINT_SZ, "mint"), (TOKEN_SZ, "token")]:
    print(f"; stride({label:9s}) = {hex(stride(d))}  ({stride(d)} bytes)")

print("\n; All assertions passed.")
